### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [AnieBee/ClusterVAR#1]
I suggest adding topics such as `time-series-analysis`, `multivariate-time-series`, `vector-autoregression`, `cluster-analysis`, `r-package` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by AnieBee** [comment]
Great suggestion, thank you!
